### ISSUE TITLE
Library cannot be embedded in nextjs

### ISSUE THREAD

**Issue by luigimannoni** [blueStragglr/react-chevron#1]
Hi, thanks for this little module.
I've tried to import this in a nextjs 12 project and I had the following error:

```
./node_modules/next/dist/build/webpack/loaders/error-loader.js):
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/react-chevron/Chevron/Chevron.js
```

The flagged url ( https://nextjs.org/docs/messages/css-npm ) reports these suggestions:

> [Why This Error Occurred](https://nextjs.org/docs/messages/css-npm#why-this-error-occurred)
> One of your dependencies (node_modules) imports a CSS file.
> 
> This normally happens when a package's source files are accidentally consumed, instead of the built package.
> 
> [Possible Ways to Fix It](https://nextjs.org/docs/messages/css-npm#possible-ways-to-fix-it)
> Reach out to the maintainer and ask for them to publish a compiled version of their dependency.
> 
> Compiled dependencies do not have references to CSS files, or any other files that require bundler-specific integrations.
> 
> The dependency should also provide instructions about what CSS needs to be imported by you, in your application.
> 
> Importing CSS files within node_modules cannot be supported because we cannot know the correct behavior:
> 
> - Should the file be consumed as Global CSS or CSS Modules?
> - If Global, in what order does the file need to be injected?
> - If Modules, what are the emitted class names? As-is, camel-case, snake case?

**Comment by blueStragglr** [comment]
Hello!
Thanks for reaching out :)
I just resolved the problem you shared.
Now `react-chevron(@1.1.1)` is also available to use with NextJS!
